#!/bin/sh

PREFIXES="^(\(backend\)|\(frontend\)|\(config\)) "

if ! grep -qE "^($PREFIXES)" "$1"; then
    echo "The commit message must start with one of the following prefixes: $PREFIXES" >&2
    exit 1
fi
